name: 📍 Nieuwe glaskunst locatie
description: Voeg een locatie toe aan de kaart
title: "[LOCATIE]: "
labels: ["inzending"]
body:
  - type: input
    id: name
    attributes:
      label: Naam locatie
    validations:
      required: true

  - type: input
    id: address
    attributes:
      label: Adres
      placeholder: Straat + plaats (bijv. Oudezijds Voorburgwal 23, Amsterdam)
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Website / bron

  - type: textarea
    id: description
    attributes:
      label: Beschrijving
      
