name: Geocode new locations

on:
  workflow_dispatch:

jobs:
  geocode:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Append simple feature
        run: |
          echo 'var json_community = {
           type": "FeatureCollection",
           "features": [
          {
          "type": "Feature",
          "properties": {
            "name": "Test locatie",
            "url": "https://example.com",
            "description": "test"
          },
          "geometry": {
            "type": "Point",
            "coordinates": [4.90, 52.37]
           }
          }
         }
       };' > docs/data/community.js
